global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using BLE_Hockey.Model;
global using BLE_Hockey.Pages;
global using BLE_Hockey.Services;
global using BLE_Hockey.Uuids;
global using BLE_Hockey.ViewModels;
global using Microsoft.Maui.ApplicationModel;
global using Plugin.BLE;
global using Plugin.BLE.Abstractions;
global using Plugin.BLE.Abstractions.Contracts;
global using Plugin.BLE.Abstractions.EventArgs;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using IAdapter = Plugin.BLE.Abstractions.Contracts.IAdapter;